### ISSUE TITLE
Issues when loaded via arg

### ISSUE THREAD

**Issue by SirVoe** [ShadauxCat/CATSFC#10]
When loaded using an arg command, no save states are shown and the settings such as frequency and scale are defaulted.

**Comment by ShadauxCat** [comment]
Seems like a simple enough thing to fix.  I'll try to have it done by tomorrow or the next day.

**Comment by Nebuleon** [comment]
Does this still happen in CATSFC 1.21 (2013-01-20)?

**Comment by Nebuleon** [comment]
Fixed by BassAceGold in commits 4ac61d443d5786db1b1e365e0005a1d5740183b0 and ea330e8f79c16894deda51509e769cbd02ff83df (2013-02-06). This fix will be in the next release of CATSFC.

**Comment by Nebuleon** [comment]
CATSFC 1.29 is now released.
