### ISSUE TITLE
Cheat selection freeze.

### ISSUE THREAD

**Issue by Rydian** [ShadauxCat/CATSFC#11]
After changing the cheats enabled for a game and playing the game, upon attempting to change a second time the emulator will either fail to apply the cheats, or will lock up.

This seems to be an issue dating from the official version of the emulator as well.

**Comment by ShadauxCat** [comment]
I'll see what I can find out.

**Comment by Nebuleon** [comment]
This appears to be fixed in commit f843d68bb65f8a532b365efc5cbdf5be65c5f517 (2012-12-24) (v 1.09).

Rydian: Can you download v 1.09 and test this, then report on this issue when you have time?
