### ISSUE TITLE
Game Genie codes not supported.

### ISSUE THREAD

**Issue by Rydian** [ShadauxCat/CATSFC#12]
The emulator does not currently support Game Genie codes (only PAR codes), this limits what can be done with it.

I wish I could find the original document I used for instructions on how GG codes are encoded, but I can't find it right now so this PHP code will have to do as it's all I have handy.
http://pastebin.com/8XUVfUZY

If you're not willing to implement them directly, it's possible for you to just change the PAR code handling to accept memory banks other than RAM (7E) so people could use the PAR equal to Game Genie codes (online converters are available and the CHT pack/converter I've made for this emulator would be updated to include those converted codes).

**Comment by ShadauxCat** [comment]
I will look into this.

**Comment by Nebuleon** [comment]
This has been added, via S9xGameGenieToRaw and via accepting the old BSNES cheat format, in commits a194b850037c03f5fb3ac1ecc9f7a99f73b84104 (2012-12-22), bb39cc82364ea00324a054ba0970bdc07ecfdeec (2012-12-23) and f843d68bb65f8a532b365efc5cbdf5be65c5f517 (2012-12-24) (v 1.09).

Tested with Super Mario World and an official Game Genie codebook.
