### ISSUE TITLE
Slow but near perfect emulation.

### ISSUE THREAD

**Issue by keine** [ShadauxCat/CATSFC#13]
Super Bomberman 2 (Slow)
Donkey Kong Country 2 (Slow with a sound distortion on overworld maps)

Shadaux? I didn't know how you wanted ROM compatibility formatted. There's probably a better way.

**Comment by ShadauxCat** [comment]
I'd prefer them each in their own individual ticket so I can close it if I finish one but not the other, but this will be fine for now.

**Comment by XXXjoseXXX** [comment]
games on chip fx is slow, as yoshi's island, star fox, is slowly

**Comment by Nebuleon** [comment]
"Slow but near perfect emulation", by keine, is a subset of the new issue #27.

Yoshi's Island is a different beast. It uses the SA1 chip which is clocked 3x as high as the SNES's main chip. While using Mode 7 and huge sprites. There will simply not be enough horsepower on the DSTWO's 396 MHz to emulate it all at 15+ FPS.
