### ISSUE TITLE
Does not go into sleep mode.

### ISSUE THREAD

**Issue by Rydian** [ShadauxCat/CATSFC#14]
The DS does not go into sleep mode when the emulator is running, neither in-game or when in a menu.  This is another inherited issue from older versions.

**Comment by Nebuleon** [comment]
With the lid, that is?

**Comment by Nebuleon** [comment]
CATSFC now sleeps when the lid is closed, to an unknown extent, as of commit 7c2a30c5b54e000106e466ba44fcc040746a0c90 (2013-01-02). This feature will go into release 1.14.

**Comment by Nebuleon** [comment]
Released.
