### ISSUE TITLE
Ability To hotkey access to Real-Time menu to buttons

### ISSUE THREAD

**Issue by princefarzan** [ShadauxCat/CATSFC#15]
It would be nice if you could hotkey the real time menu to buttons, similar to that of the normal DS games real time menu where when you press L+R+Start it will bring you to the real time menu. Instead of hitting the bottom touchscreen to bring it up because sometimes you hit it by accident when playing games which will pause your game, it would be better if access to it can be hotkeyed or set to some button combination.

**Comment by Nebuleon** [comment]
Hotkeying the main menu has been implemented in commit 44164cce8c3fa2f0f34d9c5d8c55d4cc576cbe69 (2013-01-22) (v 1.23).
