### ISSUE TITLE
No PAL mode. European games play too fast

### ISSUE THREAD

**Issue by amaro999** [ShadauxCat/CATSFC#17]
The emulator does not have support to PAL mode. It means that when the game is European it will play too fast. Of course you can always pick the American version. Unfortunately, some games do not have an American version, so they are unplayable.

**Comment by Nebuleon** [comment]
Is this issue still present in CATSFC v 1.10? And with which game?

**Comment by Nebuleon** [comment]
This issue is fixed as of commit c01c25febed921976e256d974bf97f948fe16753 (2013-01-07) and awaits the release of CATSFC 1.15.

**Comment by Nebuleon** [comment]
Released in CATSFC 1.15.
