### ISSUE TITLE
Secret Of Mana bugs

### ISSUE THREAD

**Issue by Taelis** [ShadauxCat/CATSFC#18]
Hi, 

please forgive me for my english, i'm french ^^

I tried Secret Of Mana (Seiken Densetsu 2) with different graphic modes...

I can't find one where the text is displayed correctly. 
As Well there's an issue with the layers.

How can we help to improve the compatibility with more games ?

**Comment by ShadauxCat** [comment]
Duplicate with https://github.com/ShadauxCat/CATSFC/issues/1
