### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Taelis** [ShadauxCat/CATSFC#19]
I want to propose myself to translate the interface in french...

So if you can contact me to give me everything i need to translate ^^

See you

**Comment by ShadauxCat** [comment]
Everything you need is available in the project.  Just make a project fork, edit what you need, and submit a pull request.

The file you want to edit is CATSFC/system/language.msg.  Copy the section between STARTENGLISH and ENDENGLISH, paste it at the bottom, and change that to STARTFRENCH and ENDFRENCH.  If you don't know how to edit the code to add the french language option, go ahead and submit a pull request with just that file, and I'll change the code once the translation is done.

**Comment by ShadauxCat** [comment]
Your pull request has been merged and the french translation will be in the next release.  Thanks for your contribution!
