### ISSUE TITLE
Screen scrolling with stylus

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#2]
To fix the shortcomings of the various display modes, we will replace display modes 1-3 with a single display mode that will allow movement of the screen by scrolling with the stylus to move the screen up and down.  Accessing the menu will still be achieved through a simple tap.

**Comment by amaro999** [comment]
I think this is one of the most waited features for the CATSFC. I have an opinion here though. Some games do not use L or R buttons. If you could configure the emulator to use these buttons to scroll the screen would be very nice too. So you could scroll the screen faster, without having to touch the touch screen. For example, the standard screen could be the mode 2. Whenever you press R button it changes to mode 3 (actually, it does not need to scroll, it can just skip from one mode to another). If you press R again it goes back to mode 2. The same with L button and mode 1. This is how SCUMMVM works and also DS2x86.

**Comment by ShadauxCat** [comment]
I can do that.  I'll put it in with the button remapping in version 1.4 - that way I can make sure the L button's not trying to do two things at once.

I'll update that task to add this into it.

**Comment by Nebuleon** [comment]
This is more or less moot since commit ac4de708b51da86a61da274192056e604e499e37 (2013-01-02) (v 1.13).

Since that commit, the aspect ratio setting "[4] Entire screen, anti-aliased" shows everything without needing to skip pixels or change the viewport with the stylus.
