### ISSUE TITLE
Secret of Mana, menu fonts display incorrectly.

### ISSUE THREAD

**Issue by MechaGouki** [ShadauxCat/CATSFC#28]
Secret of Mana has had an issue through every version of the DStwo emulator (it exists in Snemulds too I believe) where the emulator fails to correctly display the narrower font used in the menu screens, see the image below for an example:

![SoMfontproblem](https://f.cloud.github.com/assets/3161483/37088/8560e756-53b3-11e2-92dc-4f8de86836af.jpg)

**Comment by Nebuleon** [comment]
My progress on this bug so far has been great. I have the background working:
![mana-menu-20130101](https://f.cloud.github.com/assets/2391500/37388/d6ac52bc-543f-11e2-8353-ab6a7c2f011b.png)
But the sprites, which were bad, are still kind of bad:
![mana-menu-sprite](https://f.cloud.github.com/assets/2391500/37389/0368bb7e-5440-11e2-9231-0f6698c75c45.png)
(images are taken in CATSFC itself with the show middle option)

This bug, which is about the menu font, is thus now fixed pending a release.

**Comment by Nebuleon** [comment]
A fix for the font issue is in release 1.13.

**Comment by MechaGouki** [comment]
Awesome work! Sorry for not thanking you sooner, haven't checked my email for a couple of days. Really exciting progress on this emulator, thank you for all your time and effort!

Charlie.
