### ISSUE TITLE
Single Cheat codes displayed as multiple code

### ISSUE THREAD

**Issue by BASgamer** [ShadauxCat/CATSFC#29]
Any way to get the cheat codes with multiple codes to appear as one code. Currently anything with 2+ codes entered as "########+########+########" will output as multiple different codes you have to enable separately. It becomes a major hassle when some of the codes have 13+ lines. Thank you for your time.

**Comment by Nebuleon** [comment]
Reimplemented on top of 1.09's cheat support in commit 6794af6695b0b4a7062ee077433ef97e5d83104f (2013-02-12), pending a CATSFC release.

**Comment by Nebuleon** [comment]
Released in CATSFC 1.31 (2013-02-14).
