### ISSUE TITLE
Save menu adjustments

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#3]
The save menu will be re-worked so that the "save state" item works the same way as the "load state" item - a list of boxes that allow you to choose your save spot simply by double clicking on any of said boxes.  As such, saving state will not always put the save in the first empty box, but will let you choose which box to save in.  If you save in a box that's full, you will be given the option to overwrite that save or cancel.

**Comment by Nebuleon** [comment]
Added in commit 009019e1bfa000add70759ff0623166287466911 (2013-01-14) (v 1.19).
