### ISSUE TITLE
Low Pitch Sound?

### ISSUE THREAD

**Issue by Truebluehero** [ShadauxCat/CATSFC#34]
CATSFC seems to emulate games' sound at a lower pitch than it should be. It seems to be happening in every game I try, such as Super Mario World and Donkey Kong Country. The Supercard team version of NDSSFC doesn't seem to have this issue. Is it supposed to sound like this, could some setting be wrong, or might it be installed wrong?

**Comment by Nebuleon** [comment]
NDSSFC has crappy sound, emulating about 1 semitone higher than it should be. I have validated this sound with a real SNES playing the same cart as on CATSFC and it sounds perfect.

For more precisions, see post 413 by Rydian and 414 by the_randomizer at http://gbatemp.net/threads/ndssfc-catsfc-revival.339600/page-21#post-4553056 on the subject of CATSFC audio timing testing. the_randomizer has perfect pitch and states that the Snes9x version could be mistaken for a real SNES, and Rydian's files comparing CATSFC and Snes9x clearly show no pitch difference between their left and right channels.

**Comment by Nebuleon** [comment]
Alright, you were right.

In CATSFC 1.31, the emulation plays sound VERY slightly too low-pitched. It's not even a semitone, maybe a few cents, but by playing the same game on the TV with the real SNES and the DS with CATSFC, I was able to hear a subtle difference.

Commit 339cdb48281846943e631a36128d53b241d3c176, which was supposed to resynchronise the sound, does nothing to resynchronise the sound, but it does fix the slightly lower-pitched sound. (That commit was one line of code, it's a Snes9x setting.)

**Comment by Nebuleon** [comment]
Fixed in CATSFC 1.32.
