### ISSUE TITLE
Quick save and quick load

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#4]
I will be adding a configurable option to enable a "quick save" and "quick load" button combination - L+R+Start to quick save, L+R+Select to quick load.  (These will become customizable with the introduction of the button mapping feature in v1.4)  Pushing this button combination in-game will automatically save your game to slot 10, or load from slot 10 (if it exists), as is appropriate.

**Comment by Nebuleon** [comment]
Customisable hotkeys, global and per game, for quickly loading from and saving to state #1 are implemented in commit a8c2fcdb2c3fa0211581cc82ea8e2d93d225fd7d (2013-02-14). It will go into the upcoming CATSFC release, 1.31.

**Comment by Nebuleon** [comment]
Released in CATSFC 1.31 (2013-02-14).
