### ISSUE TITLE
Interface redesign

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#5]
I will be redesigning the entire interface with a new loading screen, new icons, a new background, and so on, to give CATSFC a visual identity separate from the original NDSSFC.

**Comment by amaro999** [comment]
I have a suggestion here. When the name of the game is too big you can´t read it entirely on the screen. Make the name of the game scroll from right to left when it is selected, so its name can be read.

**Comment by amaro999** [comment]
One more thing: When you touch the touch screen to choose the LANGUAGE, it will not change. You have to use the D-PAD to do so.

**Comment by DaVince** [comment]
File new bugs for those, amaro. The issue tracker exists for a reason. ;)

**Comment by Nebuleon** [comment]
I've updated the interface's look with Tango icons in commits ef49954182808fce75ec825399e6e2ba48e7ed48 and 4b4349ac8afb7dce6c0ca8a64a268f897a295469. They will be in the next release of CATSFC, 1.21.

**Comment by Nebuleon** [comment]
CATSFC 1.21 is now released.
