### ISSUE TITLE
Manual Frame Skip Selection

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#6]
I will be adding an option to change between automatic frame skipping and manual frame skipping, which can be set at any level from 0 to 10 (and possibly higher).

**Comment by Nebuleon** [comment]
This feature is in commit c01c25febed921976e256d974bf97f948fe16753 (2013-01-07) and awaits the release of CATSFC 1.15.

**Comment by Nebuleon** [comment]
Released in CATSFC 1.15.
