### ISSUE TITLE
Graphics Options

### ISSUE THREAD

**Issue by ShadauxCat** [ShadauxCat/CATSFC#7]
In order to aid in adjusting performance, I will add a few options to the video and audio menu that will allow the user to enable or disable certain settings, such as transparency, in order to improve performance.

**Comment by Nebuleon** [comment]
Became more or less unnecessary with CATSFC 1.25-1.29's optimisations. Transparency and esoteric SNES background modes, like ADD and SUB, weren't, and still aren't, the problem.
